//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSharp_Console_Morse_Code_Translator {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CSharp_Console_Morse_Code_Translator.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///d88888b d8888b. d8888b.  .d88b.  d8888b.
        ///88&apos;     88  `8D 88  `8D .8P  Y8. 88  `8D
        ///88ooooo 88oobY&apos; 88oobY&apos; 88    88 88oobY&apos;
        ///88~~~~~ 88`8b   88`8b   88    88 88`8b
        ///88.     88 `88. 88 `88. `8b  d8&apos; 88 `88.
        ///Y88888P 88   YD 88   YD  `Y88P&apos;  88   YD
        ///.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///db       .d88b.   .d8b.  d8888b. d888888b d8b   db  d888b
        ///88      .8P  Y8. d8&apos; `8b 88  `8D   `88&apos;   888o  88 88&apos; Y8b
        ///88      88    88 88ooo88 88   88    88    88V8o 88 88
        ///88      88    88 88~~~88 88   88    88    88 V8o88 88  ooo
        ///88booo. `8b  d8&apos; 88   88 88  .8D   .88.   88  V888 88. ~8~
        ///Y88888P  `Y88P&apos;  YP   YP Y8888D&apos; Y888888P VP   V8P  Y888P
        ///.
        /// </summary>
        internal static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///.88b  d88. d88888b d8b   db db    db
        ///88&apos;YbdP`88 88&apos;     888o  88 88    88
        ///88  88  88 88ooooo 88V8o 88 88    88
        ///88  88  88 88~~~~~ 88 V8o88 88    88
        ///88  88  88 88.     88  V888 88b  d88
        ///YP  YP  YP Y88888P VP   V8P ~Y8888P&apos;
        ///.
        /// </summary>
        internal static string Menu {
            get {
                return ResourceManager.GetString("Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///.88b  d88.  .d88b.  d8888b. .d8888. d88888b
        ///88&apos;YbdP`88 .8P  Y8. 88  `8D 88&apos;  YP 88&apos;
        ///88  88  88 88    88 88oobY&apos; `8bo.   88ooooo
        ///88  88  88 88    88 88`8b     `Y8b. 88~~~~~
        ///88  88  88 `8b  d8&apos; 88 `88. db   8D 88.
        ///YP  YP  YP  `Y88P&apos;  88   YD `8888Y&apos; Y88888P
        ///.
        /// </summary>
        internal static string Morse {
            get {
                return ResourceManager.GetString("Morse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///d8888b. d88888b .d8888. db    db db      d888888b
        ///88  `8D 88&apos;     88&apos;  YP 88    88 88      `~~88~~&apos;
        ///88oobY&apos; 88ooooo `8bo.   88    88 88         88
        ///88`8b   88~~~~~   `Y8b. 88    88 88         88
        ///88 `88. 88.     db   8D 88b  d88 88booo.    88
        ///88   YD Y88888P `8888Y&apos; ~Y8888P&apos; Y88888P    YP
        ///.
        /// </summary>
        internal static string Result {
            get {
                return ResourceManager.GetString("Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///d888888b db    db d888888b
        ///`~~88~~&apos; `8b  d8&apos; `~~88~~&apos;
        ///   88     `8bd8&apos;     88
        ///   88     .dPYb.     88
        ///   88    .8P  Y8.    88
        ///   YP    YP    YP    YP
        ///
        ///d888888b d8b   db d8888b. db    db d888888b
        ///  `88&apos;   888o  88 88  `8D 88    88 `~~88~~&apos;
        ///   88    88V8o 88 88oodD&apos; 88    88    88
        ///   88    88 V8o88 88~~~   88    88    88
        ///  .88.   88  V888 88      88b  d88    88
        ///Y888888P VP   V8P 88      ~Y8888P&apos;    YP
        ///.
        /// </summary>
        internal static string TxtInput {
            get {
                return ResourceManager.GetString("TxtInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///db    db .d8888. d88888b d8888b.
        ///88    88 88&apos;  YP 88&apos;     88  `8D
        ///88    88 `8bo.   88ooooo 88oobY&apos;
        ///88    88   `Y8b. 88~~~~~ 88`8b
        ///88b  d88 db   8D 88.     88 `88.
        ///~Y8888P&apos; `8888Y&apos; Y88888P 88   YD
        ///
        ///d888888b d8b   db d8888b. db    db d888888b
        ///  `88&apos;   888o  88 88  `8D 88    88 `~~88~~&apos;
        ///   88    88V8o 88 88oodD&apos; 88    88    88
        ///   88    88 V8o88 88~~~   88    88    88
        ///  .88.   88  V888 88      88b  d88    88
        ///Y888888P VP   V8P 88      ~Y8888P&apos;    YP
        ///.
        /// </summary>
        internal static string UserInput {
            get {
                return ResourceManager.GetString("UserInput", resourceCulture);
            }
        }
    }
}
